__author__ = 'Mehmet Burak Eker'
__email__ = 'mehmetburakeker@gmail.com'
__version__ = '0.1.0'

ACCESS_TOKEN = 'ACCESSTOKEN'
ACCESS_SECRET = 'ACCESSSECRET'
CONSUMER_KEY = 'CONSUMERKEY'
CONSUMER_SECRET = 'CONSUMERSECRET'
MAX_TWEET_COUNT=2500
TWEET_HASHTAG='WORLD'
TWEET_LANGUAGE='tr'
